[deps]

[workspace]
projects = [
  "animations",
  "annealing",
  "atom-matching",
  "bunny",
  "cpd",
  "emdb",
  "groel-subunit",
  "icp",
  "kernel_correlation",
  "nonrigid",
  "pdb",
  "py",
  "robust",
  "smm",
  "units",
  "ribosome-puzzle",
  "frame-shift",
  "box-lid",
  "biotisr",
  "EmdbHelper",
  "thinning",
]
